'use client';
import { useEffect, useRef, useState, useCallback } from 'react';
import { flushSync } from 'react-dom';
import { Lamp, Coins, Sun, Sparkles, Package, BookOpen, FlaskConical, ScrollText, ArrowRight, Search, Handshake, Shield, Leaf, Moon, ChevronRight, Eye, CircleHelp, Volume2, VolumeX, Settings, Check, Minus, Plus, Ban, WandSparkles, Hammer, Archive, ShoppingBag, LockKeyhole, RotateCcw, Download, Upload, X, Feather, TrendingUp } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { act, freshGame, currentVisitor, items, visitors, news, rent, capacity, marketPrice, validateSave, type Game, type Action, type Stock } from '@/lib/game';
const SAVE='dusklight-pawnshop-v1';
const navs=[{Icon:Handshake,label:'柜台营业'},{Icon:Package,label:'货架仓库'},{Icon:FlaskConical,label:'炼金工坊'},{Icon:BookOpen,label:'旅人手记'},{Icon:ScrollText,label:'账簿契约'}];
const factions={guild:'冒险者公会',guard:'王国卫队',night:'灰鸦夜市'};
const relation=(n:number)=>n>=10?'信赖':n>=4?'友好':n<=-5?'敌视':n<0?'戒备':'中立';
function Portrait({index,className=''}:{index:number;className?:string}){return <div role="img" aria-label="旅人立绘" className={'portrait '+className} style={{backgroundPosition:`${(index%3)*50}% ${Math.floor(index/3)*100}%`}}/>}
export default function Home(){
 const [game,setGame]=useState<Game>(freshGame),[ready,setReady]=useState(false),[tab,setTab]=useState(0),[offer,setOffer]=useState(85),[modal,setModal]=useState(''),[toast,setToast]=useState(''),[saveStatus,setSaveStatus]=useState('进度载入中'),[sound,setSound]=useState(false),[filter,setFilter]=useState('all'),[pricing,setPricing]=useState(1);
 const ref=useRef(game), audioRef=useRef<AudioContext|null>(null), fileRef=useRef<HTMLInputElement>(null);
 ref.current=game;
 const playSound=useCallback(()=>{if(!audioRef.current)return;const ctx=audioRef.current;void ctx.resume();const osc=ctx.createOscillator(),gain=ctx.createGain();osc.type='sine';osc.frequency.setValueAtTime(659,ctx.currentTime);osc.frequency.exponentialRampToValueAtTime(440,ctx.currentTime+.35);gain.gain.setValueAtTime(.04,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.5);osc.connect(gain);gain.connect(ctx.destination);osc.start();osc.stop(ctx.currentTime+.5)},[]);
 const send=useCallback((action:Action)=>{const next=act(ref.current,action);ref.current=next;setGame(next);if(next.outcome&&next.outcome!==game.outcome)setToast(next.outcome);playSound();return next},[game.outcome,playSound]);
 useEffect(()=>{try{const raw=localStorage.getItem(SAVE);if(raw){const saved=JSON.parse(raw);if(validateSave(saved)){ref.current=saved;setGame(saved)}else setToast('旧存档无法读取，已开启新篇章。')}}catch{setToast('无法读取存档。你仍然可以游玩并导出进度。')}setReady(true)},[]);
 useEffect(()=>{if(!ready)return;try{localStorage.setItem(SAVE,JSON.stringify(game));setSaveStatus('已自动保存 · 本机')}catch{setSaveStatus('无法自动保存 · 请导出')}},[game,ready]);
 useEffect(()=>{setOffer(Math.round(currentVisitor(game).ask*.85));},[game.day,game.visitorIndex]);
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),4500);return()=>clearTimeout(t)},[toast]);
 useEffect(()=>()=>{void audioRef.current?.close()},[]);
 useEffect(()=>{const ctx=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;if(!ctx?.registerTool)return;const lifecycle=new AbortController();
 const registrations=[{name:'read_pawnshop_state',title:'查看当铺',description:'Read the visible game status, current visitor, observed clues, inventory and money. No hidden identity or pricing information.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>{const s=ref.current,v=currentVisitor(s);return {day:s.day,gold:s.gold,energy:s.energy,visitor:s.visitorIndex<3?{name:v.name,asking:v.ask,item:items[v.item].name,clue:s.examined?items[v.item].clue:null,magic:s.scanned?items[v.item].magic:null}:null,stock:s.stock,ended:s.ended}}},{name:'inspect_pawnshop_item',title:'鉴定柜台物品',description:'Spend one energy to inspect the current item, using the same action as the visible inspection button.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('Expected an empty object');const s=ref.current;if(s.ended||s.resolved||s.visitorIndex>=3||s.energy<1||s.examined)throw Error('Current item cannot be inspected');const next=act(s,{type:'inspect'});flushSync(()=>{ref.current=next;setGame(next)});return {energy:next.energy,clue:next.dialogue}}}];for(const tool of registrations){try{void Promise.resolve(ctx.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}}return()=>lifecycle.abort();},[]);
 const v=currentVisitor(game),item=items[v.item],waiting=game.visitorIndex>=3,locked=game.ended||!ready;
 const doEnd=()=>{send({type:'endDay'});setModal('');setTab(0)};
 const reset=()=>{const next=freshGame();ref.current=next;setGame(next);setTab(0);setModal('');setToast('一盏新灯亮起。你的七日故事重新开始。')};
 const exportSave=()=>{const blob=new Blob([JSON.stringify(game,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`暮灯当铺-第${game.day}天.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
 const importSave=async(file?:File)=>{if(!file)return;try{if(file.size>1000000)throw Error();const next=JSON.parse(await file.text());if(!validateSave(next))throw Error();ref.current=next;setGame(next);setModal('');setToast('存档已恢复。');setTab(0)}catch{setToast('这不是有效的暮灯当铺存档。')}if(fileRef.current)fileRef.current.value=''};
 const toggleSound=()=>{if(sound){void audioRef.current?.close();audioRef.current=null;setSound(false)}else{try{audioRef.current=new AudioContext();setSound(true);playSound()}catch{setToast('当前浏览器无法播放音效。')}}};
 const inventory=game.stock.filter(st=>filter==='all'||filter==='listed'&&st.listed||filter==='hidden'&&st.hidden||filter==='rare'&&items[st.itemId].memory);
 const sellCard=(st:Stock)=>{const it=items[st.itemId];return <article className={'stock-card '+(st.hidden?'is-hidden':'')} key={st.uid}><div className="stock-top"><span className="stock-symbol">{it.symbol}</span><span className={'tag '+(it.illegal?'danger-tag':'')}>{st.hidden?'暗格中':it.illegal?'违禁品':it.fake?'仿品':it.memory?'记忆遗物':'普通商品'}</span></div><h3>{it.name}</h3><p>{it.description}</p><div className="stock-prices"><span>成本 <b>{st.paid}</b></span><span>零售价 <b>{marketPrice(game,{...st,multiplier:st.listed?st.multiplier:pricing})}</b></span></div><div className="stock-actions"><Button className={st.listed?'small-button selected':'small-button'} disabled={locked||st.hidden} onClick={()=>send({type:'list',uid:st.uid,multiplier:pricing})}>{st.listed?<Check size={14}/>:<ShoppingBag size={14}/>} {st.listed?'已上架 · 撤下':'摆上货架'}</Button><Button className="small-button" disabled={locked} onClick={()=>send({type:'hide',uid:st.uid})}><Archive size={14}/>{st.hidden?'取出':'藏匿'}</Button></div><Button className="text-button wholesale" variant="ghost" disabled={locked} onClick={()=>send({type:'sell',uid:st.uid})}>立即批发 · {Math.round(marketPrice(game,{...st,multiplier:1})*.65)} 金币 <ArrowRight size={13}/></Button></article>};
 return <main className="game-shell">
 <header className="topbar"><a className="brand" href="/" aria-label="暮灯当铺首页"><Lamp/><span>暮灯当铺<small>DUSKLIGHT PAWNSHOP</small></span></a><div className="world-clock"><Sun size={17}/> 星落历 843 年 · 霜叶月 <span>第 {game.day} 天</span></div><div className="resources"><span title="可用金币"><Coins/> <b>{game.gold}</b> 金币</span><span title="每天恢复 8 点精力"><Sparkles/> <b>{game.energy}</b><small>/ 8</small> 精力</span><Button variant="ghost" className="top-help" size="icon" aria-label="玩法帮助" onClick={()=>setModal('help')}><CircleHelp size={18}/></Button></div></header>
 <div className="game-body"><aside className="sidebar"><div className="shop-label">橡木镇 · 南街 07 号</div><nav aria-label="当铺功能">{navs.map(({Icon,label},i)=><Button key={label} title={label} aria-label={label} aria-current={tab===i?'page':undefined} className={'nav-button '+(tab===i?'active':'')} variant="ghost" onClick={()=>setTab(i)}><Icon size={19}/>{label}{tab===i&&<span className="nav-dot"/>}</Button>)}</nav><div className="sidebar-bottom"><div className="faction-label">小镇里的关系</div><p><Shield/> 王国卫队 <span title={String(game.reputation.guard)}>{relation(game.reputation.guard)}</span></p><p><Leaf/> 冒险者公会 <span title={String(game.reputation.guild)}>{relation(game.reputation.guild)}</span></p><p><Moon/> 灰鸦夜市 <span title={String(game.reputation.night)}>{relation(game.reputation.night)}</span></p><div className="sidebar-quote">「勇者的故事结束了，<br/>旧物的故事才刚刚开始。」</div><div className="sidebar-tools"><Button variant="ghost" aria-label={sound?'关闭音效':'开启音效'} title="柜台音效" onClick={toggleSound}>{sound?<Volume2 size={16}/>:<VolumeX size={16}/>}</Button><Button variant="ghost" aria-label="存档与设置" title="存档与设置" onClick={()=>setModal('settings')}><Settings size={16}/></Button><Button variant="ghost" aria-label="玩法手册" onClick={()=>setModal('help')}><CircleHelp size={16}/></Button></div></div></aside>
 <section className="main-area"><div className="section-heading"><div><div className="eyebrow">A LITTLE SHOP AFTER THE GREAT ADVENTURE</div><h1>{navs[tab].label}<span>{['门铃响了，有位旅人来访。','每件旧物，都在等一个新主人。','让沉睡的魔力重新流动。','有些相遇，比金币更值得留下。','在租金到来之前，为明天做打算。'][tab]}</span></h1></div><div className="heading-actions"><Button variant="ghost" className="mobile-settings" aria-label="存档与设置" onClick={()=>setModal('settings')}><Settings size={17}/></Button><div className="open-badge"><i/> 第 {game.day} 天 · {game.ended?'篇章已结束':waiting?'准备打烊':'营业中'}</div></div></div>
 {tab===0&&<><div className="play-grid"><div className="scene-column"><section className={'scene '+(v.portrait>=0||waiting?'other-visitor':'')}><img src="/shop-scene.png" alt={v.portrait<0&&!waiting?'银发精灵艾琳站在黄昏的当铺柜台前':'夕阳下的奇幻旧物当铺'}/>{v.portrait>=0&&!waiting&&<Portrait key={`${game.day}-${game.visitorIndex}`} index={v.portrait} className="stage-portrait"/>}<div className="scene-location"><span>橡木镇的{['午后','黄昏','薄暮','夜晚'][game.visitorIndex]}</span><small>勇者归来后的第 80 年</small></div><div className="visitor-tag"><span>{waiting?'今日的故事暂告一段落':`第 ${game.visitorIndex+1} 位来客 · 0${game.visitorIndex+1} / 03`}</span><h2>{waiting?'灯火未眠':v.name}<span>{waiting?'等待明天的旅人':v.title}</span></h2><div>{waiting?'整理货架，准备支付今天的租金。':`${factions[v.faction]} · ${game.observed?'已观察来客':'尚未观察来客'}`}</div></div><div className="scene-caption">有些东西，人类只保存一生。精灵却会保存很久。</div><span className="art-grain"/></section>
 <section className="dialogue" key={`${game.day}-${game.visitorIndex}`}><div className="dialogue-name">{waiting?'掌柜手记':v.name}<span>{waiting?'DUSKLIGHT':v.portrait<0?'ELYN':'TRAVELER'}</span>{!waiting&&<span className="patience" aria-label={`耐心 ${game.patience} 次`}>耐心 {'● '.repeat(game.patience)}{'○ '.repeat(3-game.patience)}</span>}</div><p aria-live="polite">{waiting?'“门外的脚步声慢慢远了。把要卖的东西摆上货架，把不该被看见的东西藏好……明天，又会是谁推开这扇门呢？”':`“${game.dialogue||v.line}”`}</p><div className="dialogue-actions">{!waiting&&!game.resolved&&<><Button className="text-button" variant="ghost" disabled={locked} onClick={()=>send({type:'ask'})}><Feather size={14}/>{game.asked?'再聊聊来历':'问问物品的来历'}<ChevronRight size={14}/></Button><Button className="text-button" variant="ghost" disabled={locked} onClick={()=>send({type:'observe'})}><Eye size={14}/>{game.observed?'再看一眼':'观察来客'}</Button></>}{(game.resolved||waiting)&&<Button className="text-button" variant="ghost" onClick={()=>setTab(1)}>整理货架 <ArrowRight size={14}/></Button>}</div></section>
 <div className="news-strip"><ScrollText size={15}/><span>{news[game.day-1]}</span></div></div>
 <aside className="trade-panel">{waiting?<div className="empty-counter"><Lamp size={40}/><h2>今天辛苦了</h2><p>上架的物品会在打烊时售出。别忘了预留 <b>{rent(game.day)} 金币</b>付租金。</p><Button className="primary-button" disabled={locked} onClick={()=>setModal('end')}>打烊并结算 <Moon size={16}/></Button><Button className="text-button" variant="ghost" onClick={()=>setTab(2)}>还有精力？去工坊看看</Button></div>:<><div className="panel-heading"><span>柜台上的物品</span><span className={'tag '+((game.scanned||game.examined)&&item.illegal?'danger-tag':'')}>{game.examined||game.scanned?item.fake?'仿品':item.illegal?'违禁品':'已鉴定':'待鉴定'}</span></div><div className="item-display"><span aria-hidden="true">{item.symbol}</span><div className="item-seal">{item.memory?'A MEMORY OF THE PAST':item.illegal?'MYSTERIOUS ARTIFACT':'A TRAVELER’S BELONGING'}</div></div><div className="item-title"><h2>{item.name}</h2><span>{item.category}</span></div><p className="item-description">{item.description}</p><div className="value-row"><span>预估市价</span><strong>{game.examined||game.scanned?`${Math.round(item.value*.9)} – ${Math.round(item.value*1.1)}`:'尚未鉴定'} <small>{game.examined||game.scanned?'金币':''}</small></strong></div>
 <div className="inspection-actions"><Button className="inspect-button" disabled={locked||game.resolved||game.examined||game.energy<1} onClick={()=>send({type:'inspect'})}><Search size={15}/>{game.examined?'已鉴定':'仔细鉴定'}<span>1 精力</span></Button><Button className="inspect-button" disabled={locked||game.resolved||game.scanned||game.energy<(game.upgrades.includes('lens')?1:2)} onClick={()=>send({type:'scan'})}><WandSparkles size={15}/>{game.scanned?'已感知':'感知魔力'}<span>{game.upgrades.includes('lens')?1:2} 精力</span></Button></div>
 {game.resolved?<div className="resolved-block"><div><Check size={20}/> 本次接待已结束</div><Button className="primary-button" disabled={locked} onClick={()=>send({type:'next'})}>{game.visitorIndex===2?'送走客人，整理店铺':'摇响门铃 · 下一位'}<ArrowRight size={16}/></Button></div>:<div className="offer-block"><div><span>客人开价</span><strong>{v.ask} <small>金币</small></strong></div><label htmlFor="offer">你的收购价<div className="offer-input"><Button variant="ghost" size="icon" aria-label="报价减少 5 金币" disabled={locked} onClick={()=>setOffer(x=>Math.max(1,x-5))}><Minus size={15}/></Button><input id="offer" type="number" min="1" max="9999" step="1" value={offer} onChange={e=>setOffer(Number(e.target.value))} disabled={locked}/><Button variant="ghost" size="icon" aria-label="报价增加 5 金币" disabled={locked} onClick={()=>setOffer(x=>Math.min(9999,x+5))}><Plus size={15}/></Button></div></label><Button className="primary-button" disabled={locked} onClick={()=>send({type:'offer',amount:offer})}><Handshake size={17}/> 提出报价 <ArrowRight size={16}/></Button><div className="secondary-actions"><Button variant="ghost" disabled={locked} onClick={()=>send({type:'refuse'})}>婉拒交易</Button><Button variant="ghost" disabled={locked} onClick={()=>setModal('report')}>报告卫队</Button><Button variant="ghost" disabled={locked||!game.observed} title="先观察来客，再判断是否驱魔" onClick={()=>setModal('ward')}>驱魔</Button></div>{game.day===7&&game.visitorIndex===2&&!game.returned&&game.stock.some(x=>x.itemId==='pendant')&&<Button className="return-button" disabled={locked} onClick={()=>send({type:'return'})}>将月见草吊坠还给她</Button>}</div>}<p className="hint">先了解人和物，再决定它值得多少。</p></>}</aside></div></>}
 {tab===1&&<section className="workspace-view"><div className="view-intro"><div><h2>每件旧物，都有去处。</h2><p>上架等待零售，批发立即收款。暗格里的物品不会被巡查发现。</p></div><span className="capacity"><Package size={17}/>{game.stock.length} / {capacity(game)} 格</span></div><div className="inventory-toolbar"><div className="filter-buttons">{[['all','全部'],['listed','已上架'],['hidden','暗格'],['rare','记忆遗物']].map(([key,label])=><Button variant="ghost" className={filter===key?'filter active':'filter'} key={key} onClick={()=>setFilter(key)}>{label}</Button>)}</div><label className="price-select">上架定价 <select value={pricing} onChange={e=>setPricing(Number(e.target.value))}><option value={.85}>薄利多销 · 85%</option><option value={1}>市价出售 · 100%</option><option value={1.25}>耐心等客 · 125%</option></select></label></div><div className="stock-grid">{inventory.map(sellCard)}</div>{inventory.length===0&&<div className="empty-state"><Package size={36}/><h3>这里还没有物品</h3><p>去柜台接待旅人，或到工坊购入炼金材料。</p><Button className="small-button" onClick={()=>setTab(0)}>回到柜台</Button></div>}<div className="shelf-note"><Shield size={17}/><p>第 3、4、6 天晚间巡查。未藏匿的违禁品会被没收，每件罚款 60 金币。暗格容量：{game.stock.filter(x=>x.hidden).length} / {game.upgrades.includes('cellar')?5:2}。</p></div></section>}
 {tab===2&&<section className="workspace-view"><div className="view-intro"><div><h2>把一点魔法，变成明天的路费。</h2><p>加工消耗金币与精力；成品需在仓库重新上架。</p></div><span className="capacity"><Sparkles size={17}/>{game.energy} / 8 精力</span></div><div className="recipe-grid"><article className="recipe"><FlaskConical size={32}/><div className="eyebrow">ALCHEMY · 01</div><h3>月泉净化</h3><p>月泉原液 → 净化月露</p><div className="recipe-flow"><span>原液 <b>20 G</b></span><ChevronRight/><span>加工 <b>10 G + 1 精力</b></span><ChevronRight/><span>成品 <b>85 G</b></span></div><Button className="primary-button" disabled={locked||game.energy<1||game.gold<10||!game.stock.some(x=>x.itemId==='water')} onClick={()=>send({type:'craft',uid:game.stock.find(x=>x.itemId==='water')?.uid})}>净化一瓶原液 <Sparkles size={16}/></Button><Button className="text-button" variant="ghost" disabled={locked||game.gold<20||game.stock.length>=capacity(game)} onClick={()=>send({type:'supplies'})}>购入月泉原液 · 20 金币 <Plus size={14}/></Button><small>持有原液 {game.stock.filter(x=>x.itemId==='water').length} 瓶 · 月露 {game.stock.filter(x=>x.itemId==='potion').length} 瓶</small></article><article className="recipe"><Hammer size={32}/><div className="eyebrow">RESTORATION · 02</div><h3>旧剑修复</h3><p>断刃骑士剑 → 修复的骑士剑</p><div className="recipe-flow"><span>断剑 <b>125 G</b></span><ChevronRight/><span>修复 <b>25 G + 1 精力</b></span><ChevronRight/><span>成品 <b>195 G</b></span></div><Button className="primary-button" disabled={locked||game.energy<1||game.gold<25||!game.stock.some(x=>x.itemId==='sword')} onClick={()=>send({type:'craft',uid:game.stock.find(x=>x.itemId==='sword')?.uid})}>修复一把旧剑 <Hammer size={16}/></Button><small>断剑来自旅人收购 · 持有 {game.stock.filter(x=>x.itemId==='sword').length} 把</small></article></div><div className="upgrades-heading"><h2>让这间小店，变得更好一点。</h2><span>永久升级 · 当局生效</span></div><div className="upgrade-grid">{[{key:'lens',Icon:Search,name:'精制鉴魔镜',cost:120,desc:'感知魔力消耗从 2 精力降至 1。'},{key:'shelves',Icon:Package,name:'橡木扩展货架',cost:150,desc:'库存容量从 8 格增加至 16 格。'},{key:'cellar',Icon:LockKeyhole,name:'隐秘地窖',cost:130,desc:'暗格容量从 2 件增加至 5 件。'},{key:'sign',Icon:Leaf,name:'公会认证招牌',cost:100,desc:'高价上架的物品也能保证售出。'}].map(({key,Icon,name,cost,desc})=><article className="upgrade" key={key}><Icon size={24}/><h3>{name}</h3><p>{desc}</p><Button className="small-button" disabled={locked||game.gold<cost||game.upgrades.includes(key)} onClick={()=>send({type:'upgrade',key})}>{game.upgrades.includes(key)?'已完成升级':`${cost} 金币 · 升级`}</Button></article>)}</div></section>}
 {tab===3&&<section className="workspace-view journal-view"><div className="view-intro"><div><h2>勇者归来之后，故事仍在继续。</h2><p>霜叶月的七天里，记住那些在你的柜台前停留过的人。</p></div><Feather size={34}/></div><div className="journal-intro"><span>PROLOGUE</span><h3>在很久很久以后。</h3><p>魔王倒下的第八十年，庆典上的勇者画像已经褪色。你在橡木镇租下一间旧当铺。冒险者带来破损的剑，精灵带来漫长的回忆，而某些没有影子的人，带来了不该存在的东西。</p><p>每天的租金都比昨天多一点。第七天，你有机会花 1000 金币买下店铺。在此之前，每一件物品、每一位客人，都由你决定该如何对待。</p></div><div className="journal-columns"><div><h3 className="journal-label">旅人的话 <span>{game.notes.length} 则</span></h3>{game.notes.length?game.notes.map((n,i)=><article className="journal-note" key={i}><Feather size={16}/><p>{n}</p></article>):<p className="journal-empty">问问客人货物的来历，第一则故事就会写在这里。</p>}</div><div><h3 className="journal-label">唤醒的回忆 <span>{game.memories.length} / 3</span></h3>{['pendant','ring','bell'].map(id=><article className={'memory-card '+(game.memories.includes(id)?'unlocked':'')} key={id}><span>{items[id].symbol}</span><div><h4>{game.memories.includes(id)?items[id].name:'尚未唤醒的回忆'}</h4><p>{game.memories.includes(id)?items[id].magic:'用感知魔力，倾听遗物里留下的声音。'}</p></div></article>)}<div className="journal-tip">有些遗物卖出之后，就再也找不回来了。</div></div></div></section>}
 {tab===4&&<section className="workspace-view"><div className="contract-banner"><div><span className="eyebrow">A PLACE TO CALL YOUR OWN</span><h2>在第七天，拥有自己的小店。</h2><p>每天先交租金，第七天若余款达到 1000 金币，将自动买下店铺。</p><div className="goal-progress"><i style={{width:`${Math.max(0,Math.min(100,game.gold/10))}%`}}/></div><span className="goal-number">{Math.max(0,game.gold)} / 1000 金币</span></div><ScrollText size={65}/></div><div className="ledger-stats"><article><span>可用金币</span><b>{game.gold}<small> G</small></b></article><article><span>累计交易利润</span><b>{game.profit}<small> G</small></b></article><article><span>售出物品</span><b>{game.sold}<small> 件</small></b></article><article><span>今日租金</span><b>{rent(game.day)}<small> G</small></b></article></div><div className="reputation-row">{Object.entries(factions).map(([key,label])=><div key={key}><span>{label}</span><b>{relation(game.reputation[key as keyof typeof factions])} · {game.reputation[key as keyof typeof factions]}</b></div>)}</div><div className="table-wrap"><table><thead><tr><th>日期</th><th>记账事项</th><th>金币变动</th></tr></thead><tbody>{game.log.map((l,i)=><tr key={i}><td>第 {l.day} 天</td><td>{l.text}</td><td className={l.delta>0?'positive':l.delta<0?'negative':''}>{l.delta>0?'+':''}{l.delta||'—'}</td></tr>)}</tbody></table></div></section>}
 <footer className="daybar"><div><Sun size={17}/><span>{['午后','黄昏','薄暮','夜晚'][game.visitorIndex]}</span><span className="day-track"><i style={{width:`${Math.min(100,(game.visitorIndex+1)*33.34)}%`}}/></span><small>今日来客 {Math.min(3,game.visitorIndex+1)} / 3</small></div><span>今晚租金 <b>{rent(game.day)}</b> 金币</span><Button variant="ghost" className="close-day" disabled={locked} onClick={()=>setModal('end')}>结束这一天 <ArrowRight size={15}/></Button></footer></section></div>
 <footer className="bottom-line"><span><i/>{saveStatus}</span><span>暮灯当铺 · 勇者归来之后</span><button onClick={()=>setModal('help')}>七日经营篇章 · 玩法说明</button></footer>
 {toast&&<div className="game-toast" role="status"><Lamp size={19}/><span>{toast}</span><button aria-label="关闭提示" onClick={()=>setToast('')}><X size={16}/></button></div>}
 <Dialog open={!!modal} onOpenChange={open=>{if(!open)setModal('')}}><DialogContent className="game-modal"><DialogTitle>{({help:'掌柜的第一本手册',settings:'炉火旁的小憩',end:'挂上打烊的木牌',report:'报告王国卫队',ward:'点燃驱魔符',reset:'重新点亮一盏灯'} as Record<string,string>)[modal]}</DialogTitle><DialogDescription>{({help:'七天的生意，一间小店，许多没有讲完的故事。',settings:'进度仅保存在当前浏览器，也可以导出带走。',end:'上架销售与巡查会先结算，然后支付今日租金。',report:'违禁品检举可获得奖励；误报会损害关系并需赔偿。',ward:'观察影子、呼吸和说话方式。驱魔是一次无法撤回的判断。',reset:'将清除当前七日篇章的进度。你可以先导出存档。'} as Record<string,string>)[modal]}</DialogDescription>
 {modal==='help'&&<><ol className="help-list"><li><b>看人，也看物。</b>问来历和观察免费。鉴定花 1 精力，感知魔力花 2 精力，可识破假货、禁品和遗物回忆。</li><li><b>买低，卖高。</b>调整报价，客人最多容忍三次低价。收购后去仓库上架，打烊时售出；急需钱可批发，获得市价的 65%。</li><li><b>让原料变值钱。</b>20 金币买月泉原液，加 10 金币和 1 精力，可制成市价 85 的月露。每天恢复 8 精力。</li><li><b>别让巡查找到它。</b>第 3、4、6 天查货，违禁品每件罚 60 并没收。把它藏入暗格可保住货物。</li><li><b>留意不寻常的客人。</b>观察发现拟态魔族后使用驱魔符，正确获赏 55；误判赔 45 金币。正常贸易、检举影响派系关系。</li><li><b>为自己留一个家。</b>每日租金从 40 涨至 100。第七天付租后留够 1000 金币，即可买下当铺；也可以追寻属于旅人的另一种结局。</li></ol><Button className="primary-button" onClick={()=>setModal('')}>知道了，继续营业 <ArrowRight size={16}/></Button></>}
 {modal==='settings'&&<div className="settings-actions"><Button className="small-button" onClick={exportSave}><Download size={16}/> 导出当前存档</Button><Button className="small-button" onClick={()=>fileRef.current?.click()}><Upload size={16}/> 导入存档</Button><Button className="small-button" onClick={toggleSound}>{sound?<Volume2 size={16}/>:<VolumeX size={16}/>} {sound?'关闭':'开启'}柜台音效</Button><Button className="small-button" onClick={()=>setModal('reset')}><RotateCcw size={16}/> 重新开始</Button></div>}
 {modal==='end'&&<><div className="end-details"><p>剩余未接待：<b>{waiting?0:3-game.visitorIndex-(game.resolved?1:0)} 位</b></p><p>已上架：<b>{game.stock.filter(x=>x.listed).length} 件</b></p><p>预计租金：<b>{rent(game.day)} 金币</b></p><p>现有金币：<b>{game.gold} 金币</b></p>{[3,4,6].includes(game.day)&&<p className="warning">今晚有巡查。请确认违禁品已经藏好。</p>}</div><Button className="primary-button" onClick={doEnd}>确认打烊并结算 <Moon size={16}/></Button><Button className="text-button" variant="ghost" onClick={()=>{setModal('');setTab(1)}}>先去整理货架</Button></>}
 {modal==='report'&&<><p className="confirm-copy">你要检举「{item.name}」吗？正确检举获得 25 金币，并提高卫队声望；误报赔偿最高 30 金币。</p><Button className="primary-button" onClick={()=>{send({type:'report'});setModal('')}}>确认报告卫队 <Shield size={16}/></Button></>}
 {modal==='ward'&&<><p className="confirm-copy">你观察到：{v.observation}</p><Button className="primary-button" onClick={()=>{send({type:'ward'});setModal('')}}>对 {v.name} 使用驱魔符 <Sparkles size={16}/></Button></>}
 {modal==='reset'&&<><Button className="small-button" onClick={exportSave}><Download size={16}/> 先导出存档</Button><Button className="primary-button" onClick={reset}>确认重新开始 <RotateCcw size={16}/></Button></>}
 </DialogContent></Dialog>
 <Dialog open={game.summary.length>0&&!modal} onOpenChange={open=>{if(!open&&!game.ended)send({type:'clearSummary'});else if(!open&&game.ended)send({type:'continue'})}}><DialogContent className="game-modal summary-modal" showCloseButton={!game.ended}><div className="summary-emblem">{game.ended?<Lamp size={42}/>:<Moon size={36}/>}</div><span className="eyebrow">{game.ended?'THE END OF A LITTLE CHAPTER':'WHEN THE SHOP LIGHTS GO OUT'}</span><DialogTitle>{game.ended?game.ending:`第 ${game.day-1} 天 · 打烊手记`}</DialogTitle><DialogDescription>{game.ended?'每笔交易都有价钱，有些回忆却没有。':'门铃安静了，账本翻开新的一页。'}</DialogDescription><div className="summary-list">{game.summary.map((s,i)=><p key={i}>{s}</p>)}</div><div className="summary-money"><span>余下金币</span><b>{game.gold} <small>G</small></b></div>{game.ended?<><Button className="primary-button" onClick={()=>setModal('reset')}>再开一家小店 <RotateCcw size={16}/></Button><Button className="text-button" variant="ghost" onClick={exportSave}>保存这个结局 <Download size={14}/></Button></>:<Button className="primary-button" onClick={()=>send({type:'clearSummary'})}>第 {game.day} 天 · 开门营业 <Sun size={16}/></Button>}</DialogContent></Dialog>
 <input className="sr-only" type="file" accept="application/json,.json" ref={fileRef} onChange={e=>void importSave(e.target.files?.[0])}/>
 </main>
}
